apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - serviceaccount.yaml
  - ingress.yaml
  - hpa.yaml

patches:
  - path: patch-deployment.yaml

# ตัวอย่างการ Map ECR Image Repository สำหรับ Production
# images:
#   - name: secure-api
#     newName: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/secure-api
#     newTag: prod-latest
