apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-api-sa
  annotations:
    # ARN ของ IAM Role ที่สร้างผ่าน Terraform
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/secure-api-irsa-role
